modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="cookscollection"
version="0.4.7"
displayName="Cook's Collection"
logoFile="icon.png"
credits="Developer: Baisylia | Designer: Bagels | Artist: Raspmary | Contributor Cassian"
authors="Baisylia, Bagels"
description="A Farmer's Delight addon containing various additions."

[[dependencies.cookscollection]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.cookscollection]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.cookscollection]]
modId="farmersdelight"
mandatory=true
versionRange="[1.20.1-1.2.4,)"
ordering="AFTER"
side="BOTH"
