modLoader="javafml"
loaderVersion="[47,)" # Update to Forge 47.x for 1.20.1
license="MIT License"

[[mods]]
modId="cookscollection"
version="0.4.7" # Update to match build.gradle
displayName="Cook's Collection"
logoFile="icon.png"
credits="Developer: Baisylia | Designer: Bagels | Artist: Raspmary | Contributor Cassian"
authors="Baisylia, Bagels"
description="A Farmer's Delight addon containing various additions."

[[dependencies.cookscollection]]
modId="forge"
mandatory=true
versionRange="[47,)" # Update to Forge 47.x
ordering="NONE"
side="BOTH"

[[dependencies.cookscollection]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)" # Update to 1.20.1
ordering="NONE"
side="BOTH"

[[dependencies.cookscollection]]
modId="farmersdelight"
mandatory=true
versionRange="[1.20.1-1.2.4,)" # Update to the correct Farmer’s Delight version for 1.20.1
ordering="AFTER"
side="BOTH"